### ISSUE TITLE
Questions about the success rate of experimental results in Table7

### ISSUE THREAD

**Issue by yrq0424** [ManiCM-fast/ManiCM#10]
Thank you for your insightful paper. I would like to ask whether the experimental results presented in Table 7 indicate that the teacher policy and MANICM both need to be retrained for each task individually? I appreciate your clarification on this matter.
![371834697-c4161c05-f55d-4bc4-a6e9-a6291808c3c6](https://github.com/user-attachments/assets/e123c827-7268-4093-b0ef-5a6ee7846cf9)

**Comment by GuanxingLu** [comment]
Yes, for each random seed, we pass through the whole pipeline, i.e., re-train both DP3 and ManiCM.
