### ISSUE TITLE
simple_dp3 implementation with ManiCM

### ISSUE THREAD

**Issue by keitheorem** [ManiCM-fast/ManiCM#3]
Hello, may I ask how do I implement ManiCM with simple_dp3?

**Comment by gao-zifeng** [comment]
Thank you for your attention. Here is the implementation.
Import `ConditionalUnet1D` from `simple.conditional_unet1d` instead of `conditional_unet1d` and use the annotated `down_dims` in `dp3.yaml` and `dp3_cm.yaml`.

**Comment by keitheorem** [comment]
Thank you!
