### ISSUE TITLE
num_inference_step

### ISSUE THREAD

**Issue by zql-kk** [ManiCM-fast/ManiCM#5]
hi, great job, have you try to setting the num_inference_step=1 in original DP3? The num_inference_step is set to 10 in this experiment, but i found that num_inference_step=1 is also work well. If setting the num_inference_step=1 in DP3, the inference time is almost same.

**Comment by runjie-yan** [comment]
hi, great job, I have samilar concerns on the inference steps. I also found that DP3 seems to work well with num_inference_step=1. I think one possible reason is the generated datasets in the virtual benchmark is not diverse enough and maybe training diffusion model on it is even unnecessary?

**Comment by gao-zifeng** [comment]
We did try setting fewer inference steps on dp3, with num_inference_step=4 resulting in an average success rate of 72.4%.
