### ISSUE TITLE
Questions about the success rate of experimental results

### ISSUE THREAD

**Issue by BofangJia** [ManiCM-fast/ManiCM#8]
In Table 7 of the paper, I have several questions to consult you, which are not consistent with the experimental results I have obtained.

Q1: For the code you provided, I did about 2 experiments on average, but the results of these two times are not as good as those provided in your table. May I ask whether the results in the table mean that you conducted separate debugging for each task?

Q2: Similarly, I found that for the success rate, that is, the data calculated in the table, is it the average success rate in the 3000epoch, or the highest success rate, or the success rate evaluated after the last training for the 2800epoch?

Q3: Similarly, I also found that the results may not always be integers, and what does the '+-' symbol in your table mean?
![RS0YKGCMO KAKFIT LJA803](https://github.com/user-attachments/assets/c4161c05-f55d-4bc4-a6e9-a6291808c3c6)

**Comment by gao-zifeng** [comment]
Thank you for your feedback. 
A1: Our experimental results are the average S5 results of the same hyperparameters under three different seeds, without any fine-tuning for a specific task. If your experimental results differ significantly, there may be some problems with the parameters or simulation environment.
A2: The S5 result follows the DP3 work, which means that there were 15 evaluations during the model training process, and we chose the highest five to take the average. 
A3: The success rates in the table have been rounded to the nearest integer. The '+-' in the table represents the standard deviation.
